### ISSUE TITLE
BYODNS Setup

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/sunstar-foundation#107]
References:
 - https://git.corp.adobe.com/experience-platform/franklin-delivery-cdn/issues/124
 - https://www.aem.live/docs/byo-dns

- [ ] https://www.sunstar-foundation.org BYODNS setup along with its root domain mapping - Issue raised: https://git.corp.adobe.com/experience-platform/franklin-delivery-cdn/issues/142
- [ ] Along with its root domain mapping

**Comment by jindaliiita** [comment]
@meejain Can you please also include me to this issue

**Comment by meejain** [comment]
FQDN -
https://www.sunstar-foundation.org/

Franklin Origin - https://main--sunstar-foundation--hlxsites.hlx.live/

Plus we need to make sure to make the root domain (without www) also working - https://sunstar-foundation.org/ 
Will confirm the Go Live date shortly which should be very much the last week of Feb'23.

**Comment by meejain** [comment]
As per https://git.corp.adobe.com/experience-platform/franklin-delivery-cdn/issues/142

<img width="1113" alt="image" src="https://github.com/hlxsites/sunstar-foundation/assets/37831850/62dfc7a6-9d83-4338-8e75-1e3d5797e0ad">

**Comment by meejain** [comment]
Now we have got both CNAME entries for www & root domains . Now at the time of DNS switch since we need https://sunstar-foundation.org/ to redirect to https://www.sunstar-foundation.org/ . Customer need to follow the steps -  A records to these four IP addresses: 151.101.2.117, 151.101.66.117, 151.101.130.117, and 151.101.194.117

**Comment by sdmcraft** [comment]
Closing since the site is already live..
